spring:
  main:
    banner-mode: log
  application:
    name: App
  profiles:
    active: PROD
#    active: DEV
#  thymeleaf:
#    cache: false
#    check-template: true
#    check-template-location: true
#    enabled: true
#    encoding: UTF-8
#    mode: HTML
#    prefix: classpath:/templates/
#    suffix: .html

#  jpa:
#    show-sql: false
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.SQLServer2012Dialect
#  datasource:
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://localhost:1433;databaseName=Users;
##    url: jdbc:jdbc:sqlserver://172.17.0.2:1433;databaseName=Test;
#    username: sa
#    password: SaUser123456

#user:
#  datasource:
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://localhost:1433;databaseName=Users;
#      #    url: jdbc:jdbc:sqlserver://172.17.0.2:1433;databaseName=Test;
#    username: sa
#    password: SaUser123456



